### ISSUE TITLE
关于版本

### ISSUE THREAD

**Issue by wsyhhhh** [zaxlct/MxOnline_Django#12]
你好，我用的是12-1那个分支版本，django1.9,但是python manager.py migrate的时候有一个数据库users_banner的表没有生成

**Comment by kele59** [comment]
@wsyhhhh 
检查下 `/apps/users/models.py` 里，是否注册了 `Banner ` 表了呢？
然后，
先   ` python manage.py makemigrations`
再	`python manage.py migrate`
试试。

**Comment by wsyhhhh** [comment]
Models.py里住注册了banner表，在python manage.py migrate这步时出现了问题
   Applying courses.0001_initial... OK
  Applying courses.0002_auto_20170108_1256... OK
  Applying courses.0003_course_course_org... OK
  Applying courses.0004_course_category...Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 350, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 342, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/migrate.py", line 200, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 92, in migrate
    self._migrate_all_forwards(plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 121, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 198, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/migration.py", line 123, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/operations/fields.py", line 62, in database_forwards
    field,
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/mysql/schema.py", line 50, in add_field
    super(DatabaseSchemaEditor, self).add_field(model, field)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/schema.py", line 396, in add_field
    self.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/schema.py", line 110, in execute
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/mysql/base.py", line 112, in execute
    return self.cursor.execute(query, args)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
django.db.utils.OperationalError: (1067, "Invalid default value for 'category'")

**Comment by kele59** [comment]
错误写的明白啊，最后一行：
`Invalid default value for 'category`
检查一下 `apps/organization/models.py` 里 ，`category` 是否设置了正确的默认值。

**Comment by wsyhhhh** [comment]
设置了默认值，我还和master版本对比也是一样的默认值，还用了9-1的版本也有相同的问题

**Comment by kele59** [comment]
@wsyhhhh 
有个最简单粗暴的解决办法，把数据库删了，重新建一个。

**Comment by kele59** [comment]
看一下我最近的这两次提交，是否能解决你的问题
@wsyhhhh 

https://github.com/zaxlct/MxOnline_Django/commit/3a36a907655195db96d907f51dab7fc62ebc9511
https://github.com/zaxlct/MxOnline_Django/commit/a6e7f6dc6b8f4372b917b5ba054d95b3dab60e72
