### ISSUE TITLE
python3 安装完xadmin 出现NameError: name 'reload' is not defined

### ISSUE THREAD

**Issue by maojiaxu8039** [zaxlct/MxOnline_Django#7]
Traceback (most recent call last):
  File "<input>", line 5, in <module>
  File "C:\Users\maoji\Envs\xadmin\lib\site-packages\django\__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\maoji\Envs\xadmin\lib\site-packages\django\apps\registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "C:\Users\maoji\Envs\xadmin\lib\site-packages\django\apps\config.py", line 90, in create
    module = import_module(entry)
  File "C:\Users\maoji\Envs\xadmin\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "C:\Users\maoji\Envs\xadmin\lib\site-packages\xadmin\__init__.py", line 4, in <module>
    from xadmin.sites import AdminSite, site
  File "D:\Program Files (x86)\JetBrains\PyCharm 5.0.3\helpers\pydev\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\maoji\Envs\xadmin\lib\site-packages\xadmin\sites.py", line 10, in <module>
    reload(sys)
NameError: name 'reload' is not defined

**Comment by kele59** [comment]
django 版本多少
python 具体版本多少
测试 python 3.5 + django 1.10 是没问题的，django 1.11 有很多问题，不建议使用。

**Comment by maojiaxu8039** [comment]
django 1.9.8
python 3.6 3.5 我都试验了 我把你的代码下载下来看了一下发现xadmin\sites.py不一样
xadmin现在的版本代码是这个
reload(sys)
sys.setdefaultencoding("utf-8")
这个是我从你项目中看到的
if six.PY2 and sys.getdefaultencoding()=='ascii':
    import imp
    imp.reload(sys)
    sys.setdefaultencoding("utf-8")

**Comment by kele59** [comment]
@maojiaxu8039 
我和多个人测试，这个项目里的 xadmin ，在 Django 1.10 和 Python 3.5 下是没问题的
